<div id="ckepop" style="margin-top: 20px;inline-height: 25px;padding: 5px 0 5px 0">
<span class="jiathis_txt">分享到：</span>
<a class="jiathis_button_qzone">QQ空间</a>
<a class="jiathis_button_tsina">新浪微博</a>
<a class="jiathis_button_renren">人人网</a>
<a class="jiathis_button_kaixin001">开心网</a>
<a class="jiathis_button_tqq">腾讯微博</a>
<a class="jiathis_button_t163">网易微博</a>
<a class="jiathis_button_tsohu">搜狐微博</a>
<a class="jiathis_button_taobao">淘江湖</a>
<a class="jiathis_button_xiaoyou">朋友网</a>
</div>
<script type="text/javascript" >
var jiathis_config={
    data_track_clickback:true,
    hideMore:true
}
</script>
<script type="text/javascript" src="http://v2.jiathis.com/code/jia.js" charset="utf-8"></script>
<div>&nbsp;</div>