<div id="ckepop">
<a class="jiathis_button_qzone"> </a>
<a class="jiathis_button_tsina"> </a>
<a class="jiathis_button_renren"> </a>
<a class="jiathis_button_kaixin001"> </a>
<a class="jiathis_button_tqq"> </a>
<a class="jiathis_button_t163"> </a>
<a class="jiathis_button_tsohu"> </a>
<a class="jiathis_button_taobao"> </a>
<a class="jiathis_button_xiaoyou"> </a>
</div>
<script type="text/javascript" >
var jiathis_config={
    data_track_clickback:true,
    hideMore:true
}
</script>
<script type="text/javascript" src="http://v2.jiathis.com/code/jia.js" charset="utf-8"></script>